version: '3.8'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HostDomain=${VAR_DOMAIN}
      - FrontendPort=${VAR_FRONTEND_PORT}
      - TelegramSettings__Token=${VAR_TELEGRAM_API_TOKEN}
      - TelegramSettings__AdminChatId=${VAR_TELEGRAM_ADMIN_CHAT_ID}
      - VAR_TELEGRAM_CHAT_ID=${VAR_TELEGRAM_ADMIN_CHAT_ID}
      - JwtOptions__SecretKey=${VAR_JWT_SECRET_KEY}
      - ConnectionStrings__DefaultConnection=${VAR_POSTGRES_CONNECTIONSTRINGS}
      - DatabaseSettings__ConnectionString=${VAR_MONGO_CONNECTIONSTRINGS}

  frontend:
    build:
      args:
        - VITE_VAR_URL=${VAR_URL}
        - VITE_VAR_FRONTEND_PORT=${VAR_FRONTEND_PORT}
    environment:
      - VITE_VAR_URL=${VAR_URL}
      - VITE_VAR_FRONTEND_PORT=${VAR_FRONTEND_PORT}

  db:
    environment:
      - POSTGRES_USER=${VAR_POSTGRES_USER}
      - POSTGRES_PASSWORD=${VAR_POSTGRES_PASSWORD}
      - POSTGRES_DB=${VAR_POSTGRES_DATABASE}

  pg_admin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${VAR_PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${VAR_PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1

  seq:
    environment:
      ACCEPT_EULA: Y

  jaeger:
    environment:
      - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED:"true"

  proxy:
    environment:
      - VAR_DOMAIN=${VAR_DOMAIN}
      - VAR_FRONTEND_PORT=${VAR_FRONTEND_PORT}

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${VAR_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${VAR_MONGO_PASSWORD}

  mongo-express:
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${VAR_MONGO_EXPRESS_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${VAR_MONGO_EXPRESS_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=${VAR_MONGO_CONNECTIONSTRINGS}
      - ME_CONFIG_BASICAUTH_USERNAME=${VAR_MONGO_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${VAR_MONGO_PASSWORD}
