version: '3'

services:
  backend:
    container_name: api
    image: ${DOCKER_REGISTRY-}backend
    ports:
      - ${VAR_BACKEND_PORT}:80
    depends_on:
      - db
    build:
      context: backend/HeartmadeCandles/
      dockerfile: Dockerfile
    volumes:
      - .backend/HeartmadeCandles/HeartmadeCandles.API/StaticFiles:/app/StaticFiles

  frontend:
    container_name: client
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: frontend/heartmage-candles
      dockerfile: Dockerfile
    ports:
      - ${VAR_FRONTEND_PORT}:${VAR_FRONTEND_PORT}

  db:
    container_name: pg_db
    image: postgres:15.2
    ports:
      - ${VAR_POSTGRES_PORT}:${VAR_POSTGRES_PORT}
    restart: always

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:6.21
    ports:
      - ${VAR_PGADMIN_PORT}:80

  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - ${VAR_SEQ_PORT}:80

  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
      - db
      - pg_admin
      - seq
      - jaeger
