version: '3'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VAR_BACKEND_PORT=${VAR_BACKEND_PORT}
      - VAR_TELEGRAM_API_TOKEN=${VAR_TELEGRAM_API_TOKEN}
      - VAR_TELEGRAM_CHAT_ID=${VAR_TELEGRAM_CHAT_ID}
      - VAR_POSTGRES_SERVER=${VAR_POSTGRES_SERVER}
      - VAR_POSTGRES_PORT=${VAR_POSTGRES_PORT}
      - VAR_POSTGRES_DATABASE=${VAR_POSTGRES_DATABASE}
      - VAR_POSTGRES_USER=${VAR_POSTGRES_USER}
      - VAR_POSTGRES_PASSWORD=${VAR_POSTGRES_PASSWORD}
      - VAR_SEQ_PORT=${VAR_SEQ_PORT}
      - VAR_JWT_SECRET_KEY=${VAR_JWT_SECRET_KEY}
      - VAR_ADMIN_LOGIN=${VAR_ADMIN_LOGIN}
      - VAR_ADMIN_PASSWORD=${VAR_ADMIN_PASSWORD}

  frontend:
    environment:
      - VAR_URL=${VAR_URL}
      - VAR_BACKEND_PORT=${VAR_BACKEND_PORT}

  db:
    environment:
      - POSTGRES_USER=${VAR_POSTGRES_USER}
      - POSTGRES_PASSWORD=${VAR_POSTGRES_PASSWORD}
      - POSTGRES_DB=${VAR_POSTGRES_DATABASE}

  pg_admin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${VAR_PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${VAR_PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1

  seq:
    environment:
      ACCEPT_EULA: Y

  jaeger:
    environment:
      - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED:"true"
