version: '3.8'

services:
  backend:
    container_name: api
    image: ${DOCKER_REGISTRY-}backend
    ports:
      - ${VAR_BACKEND_PORT}:80
    depends_on:
      - db
    build:
      context: backend/HeartmadeCandles/
      dockerfile: Dockerfile
    volumes:
      - ./backend/HeartmadeCandles/HeartmadeCandles.API/StaticFiles:/app/StaticFiles

  frontend:
    container_name: client
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: frontend/heartmage-candles
      dockerfile: Dockerfile.prod
    ports:
      - ${VAR_FRONTEND_PORT}:${VAR_FRONTEND_PORT}
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./frontend/heartmage-candles:/app

  db:
    container_name: pg_db
    image: postgres:15.2
    ports:
      - ${VAR_POSTGRES_PORT}:${VAR_POSTGRES_PORT}
    restart: always

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:6.21
    ports:
      - ${VAR_PGADMIN_PORT}:80

  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - ${VAR_SEQ_PORT}:80

  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 4318:4318

  proxy:
    container_name: proxy
    image: nginx:latest
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./nginx/robots.txt:/etc/nginx/robots.txt
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 80:80
      - 443:443
      - 16686:16686
    depends_on:
      - backend
      - frontend
      - db
      - pg_admin
      - seq
      - jaeger
      - filebrowser

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - ${VAR_MONGO_PORT}:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - ${VAR_MONGO_EXPRESS_PORT}:8081
    depends_on:
      - mongo

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - ${VAR_FILEBROWSER_PORT}:80
    volumes:
      - ./backend/HeartmadeCandles/HeartmadeCandles.API/StaticFiles:/srv
