version: '3'

services:
  api:
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '5000:80'
    depends_on:
      - pg_db
    build:
      context: backend/HeartmadeCandles/
      dockerfile: Dockerfile
    volumes:
      - .backend/HeartmadeCandles/HeartmadeCandles.API/StaticFiles:/app/StaticFiles

  client:
    container_name: client
    build:
      context: frontend/heartmage-candles
      dockerfile: Dockerfile
    ports:
      - '5173:5173'

  pg_db:
    container_name: pg_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pg_db
    image: postgres:15.2
    ports:
      - '5432:5432'
    restart: always

  pg_admin:
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.root
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
    image: dpage/pgadmin4:6.21
    ports:
      - '5433:80'

  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    ports:
      - '5341:80'

  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - api
      - client
      - pg_db
      - pg_admin
      - seq
