FROM node:18.15.0 AS builder

ARG VITE_VAR_URL
ARG VITE_VAR_FRONTEND_PORT

ENV VITE_VAR_URL=$VITE_VAR_URL
ENV VITE_VAR_FRONTEND_PORT=$VITE_VAR_FRONTEND_PORT

WORKDIR /app

COPY package.json .

RUN npm i

COPY . .

RUN npm run build

FROM nginx:latest

COPY /nginx/default.conf /etc/nginx/nginx.conf

COPY --from=builder /app/dist /usr/share/nginx/html