FROM node:18.15.0 AS builder

WORKDIR /app

COPY package.json .

RUN npm i

COPY . .

RUN npm run build

FROM nginx:latest

EXPOSE 5173

COPY /nginx/default.conf /etc/nginx/nginx.conf

COPY --from=builder /app/dist /usr/share/nginx/html