version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: HeartmadeCandles.API/Dockerfile

  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: ../Frontend/heartmade-candles
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline
      